### ISSUE TITLE
Errors on backend at each transaction.

### ISSUE THREAD

**Issue by julienanquetil** [wl-online-payments-direct/plugin-magento-core#9]
For each transaction (successfully done)
we got entries like that one on the backend

![Capture d’écran 2022-12-16 à 07 38 24](https://user-images.githubusercontent.com/1108170/208038410-07785a53-bae2-4e4c-a3a2-a0293b939b45.png)

Also transaction data from the backend are empty

![Capture d’écran 2022-12-16 à 07 42 59](https://user-images.githubusercontent.com/1108170/208038512-b04389d4-8b5d-4cfc-b973-75b9b33de494.png)

and we're unable to get the email with all payments details like
![Capture d’écran 2022-12-16 à 07 44 26](https://user-images.githubusercontent.com/1108170/208038970-4d255e33-aa4c-479c-b9a9-a4aba4612888.png)

So maybe it's not fully developed yet ?
any advice to fix this issues ?

cc @marionhsf

**Comment by mathieubroekaert** [comment]
Hello @julienanquetil 
The logs you see there simply mean that two calls were unsuccessful : 
- loading of the iFrame to process credit card payments
- Retrieving of the payment method lists for redirect payments (single payment buttons)

Could you confirm how you managed the successful payment ? Was it using Hosted Checkout, so in a full redirect mode ? Was this transaction already processed using this module ?

Globally, I would advise to double check the API keys & secret to make sure the connection to the platform is correctly made (doc: https://support.direct.worldline-solutions.com/en/documentation/api/authentication)

Regarding your second point, if not mistaken this is an email coming from Worldline/Ingenico itself. The API's used here do not manage the emails from Worldline directly. If you wish to send an email to your customers or yourself, you will need to use Magento email systems to achieve this.

**Comment by julienanquetil** [comment]
hi !
We're using the "Worldline_CreditCard" module (so credit card iframe), the redirect payment is disabled as the hosted checkout.

so basically customer get the iframe with CC detail to enter on checkout (card number / cvv / expiration date) and a button "place order", JS made his stuff and send customer back to "onepagesuccess" with the regular magento thank you message.

the api key is working as expected (also tested the check connection on the backend with success)

yes the emails was sent from ingenico, and "hooking" it to magento itself can't be done as we didn't get the feedback stored in payment details as mentioned in my 2nd screen, it's "empty"
But I i put the worldline debug mode to on, i can see the response in the log (but like nothing saved in DB ?)

thanks for your help.

**Comment by mathieubroekaert** [comment]
Hello !

Thank you for the feedback. In order to dig further, I would have several questions : 
- What version of Magento & Worldline plugin are you using ?
- Have all dependencies been installed ?
- In Magento logs (not the ones you have shared), do you see the callback of the webhooks ?
- Just for the sake of testing, could you try again using this card : 4874970686672022 (this is a test card that will trigger a 3DS challenge flow) and confirm whether you see a "waiting" page ?
- Are there any other plugins installed on your Magento instance ? There could also be an interaction there...

In my opinion, webhooks are not correctly received/managed, which prevents the order creation flow to occur. Could you also check, from a firewall perspective, if all IP's are correctly whitelisted ? Documentation : https://support.direct.worldline-solutions.com/en/best-practices/security/firewall/ 

Waiting for your feedback.

**Comment by julienanquetil** [comment]
Hi,
we're on 2.4.3-p3 and the worldline plugin  is  2.2.3 i see that instance din't get the latest one ( "worldline/module-magento-payment": "2.2.3")

Found on the log

[2022-12-23 15:02:10] main.CRITICAL: Error when running a cron job {"exception":"[object] (RuntimeException(code: 0): Error when running a cron job at /var/www/html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:368, TypeError(code: 0): Argument 1 passed to Worldline\\PaymentCore\\Model\\Order\\Creation\\OrderCreationProcessor::placeOrder() must be of the type string, null given, called in /var/www/html/vendor/worldline/module-magento-payment-core/Model/Order/Creation/OrderCreationProcessor.php on line 46 at /var/www/html/vendor/worldline/module-magento-payment-core/Model/Order/Creation/OrderCreationProcessor.php:50)"} []

Maybe it's an already fixed one on latest release ?

As i'm off right now for xmas, will make some investigation early 23 :)


Thanks

**Comment by WorldlineMagentoTeam** [comment]
Hello, Julien. Please, try the latest versions of the modules. It should help. If not, please, let us know which issues you have.
Thank you! For now, the current ticket will be closed.
